name: Sync Master to Public Repo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push to Public Repo
        run: |
          git remote set-url public https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/legatimatteo/chartwallet.git
          git push -f public master
