name: Sync Master to Public Repo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add remote for public repo
        run: |
          git remote add public https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/legatimatteo/chartwallet.git

      - name: Push to Public Repo
        run: |
          git fetch public
          git push -f public master

      - name: Push to Public Repo
        run: |
          git fetch public
          git push -f public master
